//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Player/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""MovementActions"",
            ""id"": ""23ff5359-826c-432a-b71e-448292694f3c"",
            ""actions"": [
                {
                    ""name"": ""MovementInputs"",
                    ""type"": ""PassThrough"",
                    ""id"": ""db760afb-21c8-4207-8e4a-fc0a7f84a528"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c825cf91-ceb6-46ac-a9da-ef105230b8dd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""eb4e694d-19e6-4319-90b8-972fabbbbf0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d3284358-98a0-4067-8198-f18f39f30d3b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementInputs"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""35780e42-b708-40ae-bdf3-1c4ab8db1183"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a2b3a781-96a6-42b3-9818-3fa03b0462e6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a6be4624-1cdf-4b53-afee-bcda6208363a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b136e8c5-1949-4c13-a7f9-66c9de70a384"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9be49a08-8a2a-406b-9df8-e9ee08538f14"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f0fcd03-e1c6-43cc-8382-513864e8a81e"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ca87b70-71c1-4930-8178-da06d6699852"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InteractionActionMap"",
            ""id"": ""a95ce8b9-8fec-4792-b7b3-f03a76408487"",
            ""actions"": [
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""22cdb5e8-d3f2-4c0d-ade0-e8a9dde30a3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""cb68e9fc-5389-4361-8f1a-1e4a26d2c0e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8eb20e93-52ce-4ee7-b829-c0bd06195c41"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a12fadd-1371-4158-904e-78fb7181d0d9"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17f377b8-d3bd-412a-b203-89c1da93bd8d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MovementActions
        m_MovementActions = asset.FindActionMap("MovementActions", throwIfNotFound: true);
        m_MovementActions_MovementInputs = m_MovementActions.FindAction("MovementInputs", throwIfNotFound: true);
        m_MovementActions_Camera = m_MovementActions.FindAction("Camera", throwIfNotFound: true);
        m_MovementActions_Interact = m_MovementActions.FindAction("Interact", throwIfNotFound: true);
        // InteractionActionMap
        m_InteractionActionMap = asset.FindActionMap("InteractionActionMap", throwIfNotFound: true);
        m_InteractionActionMap_Continue = m_InteractionActionMap.FindAction("Continue", throwIfNotFound: true);
        m_InteractionActionMap_Interact = m_InteractionActionMap.FindAction("Interact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MovementActions
    private readonly InputActionMap m_MovementActions;
    private List<IMovementActionsActions> m_MovementActionsActionsCallbackInterfaces = new List<IMovementActionsActions>();
    private readonly InputAction m_MovementActions_MovementInputs;
    private readonly InputAction m_MovementActions_Camera;
    private readonly InputAction m_MovementActions_Interact;
    public struct MovementActionsActions
    {
        private @PlayerInputs m_Wrapper;
        public MovementActionsActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovementInputs => m_Wrapper.m_MovementActions_MovementInputs;
        public InputAction @Camera => m_Wrapper.m_MovementActions_Camera;
        public InputAction @Interact => m_Wrapper.m_MovementActions_Interact;
        public InputActionMap Get() { return m_Wrapper.m_MovementActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementActionsActions set) { return set.Get(); }
        public void AddCallbacks(IMovementActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_MovementActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MovementActionsActionsCallbackInterfaces.Add(instance);
            @MovementInputs.started += instance.OnMovementInputs;
            @MovementInputs.performed += instance.OnMovementInputs;
            @MovementInputs.canceled += instance.OnMovementInputs;
            @Camera.started += instance.OnCamera;
            @Camera.performed += instance.OnCamera;
            @Camera.canceled += instance.OnCamera;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IMovementActionsActions instance)
        {
            @MovementInputs.started -= instance.OnMovementInputs;
            @MovementInputs.performed -= instance.OnMovementInputs;
            @MovementInputs.canceled -= instance.OnMovementInputs;
            @Camera.started -= instance.OnCamera;
            @Camera.performed -= instance.OnCamera;
            @Camera.canceled -= instance.OnCamera;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IMovementActionsActions instance)
        {
            if (m_Wrapper.m_MovementActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMovementActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_MovementActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MovementActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MovementActionsActions @MovementActions => new MovementActionsActions(this);

    // InteractionActionMap
    private readonly InputActionMap m_InteractionActionMap;
    private List<IInteractionActionMapActions> m_InteractionActionMapActionsCallbackInterfaces = new List<IInteractionActionMapActions>();
    private readonly InputAction m_InteractionActionMap_Continue;
    private readonly InputAction m_InteractionActionMap_Interact;
    public struct InteractionActionMapActions
    {
        private @PlayerInputs m_Wrapper;
        public InteractionActionMapActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Continue => m_Wrapper.m_InteractionActionMap_Continue;
        public InputAction @Interact => m_Wrapper.m_InteractionActionMap_Interact;
        public InputActionMap Get() { return m_Wrapper.m_InteractionActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InteractionActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IInteractionActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_InteractionActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InteractionActionMapActionsCallbackInterfaces.Add(instance);
            @Continue.started += instance.OnContinue;
            @Continue.performed += instance.OnContinue;
            @Continue.canceled += instance.OnContinue;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IInteractionActionMapActions instance)
        {
            @Continue.started -= instance.OnContinue;
            @Continue.performed -= instance.OnContinue;
            @Continue.canceled -= instance.OnContinue;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IInteractionActionMapActions instance)
        {
            if (m_Wrapper.m_InteractionActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInteractionActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_InteractionActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InteractionActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InteractionActionMapActions @InteractionActionMap => new InteractionActionMapActions(this);
    public interface IMovementActionsActions
    {
        void OnMovementInputs(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IInteractionActionMapActions
    {
        void OnContinue(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
}
